name: Deploy CloudFormation Stack

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: dummy
          aws-secret-access-key: dummy
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name s3-sqs-lambda-stack
